### ISSUE TITLE
[PE-D][Tester C] Comment cannot be viewed in full if too long

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-1/tp#177] opened 2024-04-05 21:02 UTC
If the comment is too long, the comment is abbreviated you cannot view the comment in full, which can cause issues with using HireHub.
![Screenshot 2024-04-05 at 5.41.38 PM.png](https://raw.githubusercontent.com/peterXGD/ped/main/files/a8ed6cac-b685-4973-a347-1a3361f90935.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: peterXGD/ped#7

**Comment by leeweiming3** [comment] 2024-04-06 13:33
Duplicate of #149

**Closed** 2024-04-12 12:38 UTC
