### ISSUE TITLE
[PE-D][Tester D] Title of application is not updated

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-1/tp#183] opened 2024-04-05 21:48 UTC
**To reproduce:**
1. Launch Hirehub
1. Observe the name of the application on the taskbar at the top of the window.

**Exptected:**
The name should be changed to match the product, Hirehub

**Actual:**
The name is still titled "Address App":

![image.png](https://raw.githubusercontent.com/ruijietay/ped/main/files/0adbca68-7709-4efe-8998-ed3398d42cb6.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: ruijietay/ped#15

**Comment by leeweiming3** [comment] 2024-04-06 13:46
Duplicate of #175

**Closed** 2024-04-06 13:47 UTC
